# Generated by Django 3.0.4 on 2020-04-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExample',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'product_example',
                'managed': False,
            },
        ),
    ]
